spring:
 datasource:
  url: jdbc:mysql://localhost:3306/cmatchapp
  username: root
  password: root
 jpa:
  hibernate:
    naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
   
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
server:
 port: 8088
