spring:
 datasource:
   url: jdbc:mysql://localhost:3306/cmatchapp
   username: root
   password: root
 jpa:
   hibernate:
    naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    ddl-auto: update
   show-sql: true
server:
 port: 8089